// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: booking.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookingClient is the client API for Booking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookingClient interface {
	RegisterSearchFlight(ctx context.Context, in *SearchFlightRequest, opts ...grpc.CallOption) (*SearchFlightResponse, error)
	RegisterSearchSelect(ctx context.Context, in *SearchSelectRequest, opts ...grpc.CallOption) (*SearchSelectResponse, error)
	RegisterTravellerDetails(ctx context.Context, in *TravellerRequest, opts ...grpc.CallOption) (*TravellerResponse, error)
	RegisterLoginRequest(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RegisterUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	VerifyUser(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// rpc calls for confirmed booking users
	RegisterPNRLogin(ctx context.Context, in *PNRLoginRequest, opts ...grpc.CallOption) (*PNRLoginResponse, error)
	RegisterSelectSeat(ctx context.Context, in *SeatSelectRequest, opts ...grpc.CallOption) (*SeatSelectResponse, error)
	// rpc calls for booking
	RegisterConfirmBooking(ctx context.Context, in *ConfirmBookingRequest, opts ...grpc.CallOption) (*ConfirmBookingResponse, error)
	RegisterOnlinePayment(ctx context.Context, in *OnlinePaymentRequest, opts ...grpc.CallOption) (*OnlinePaymentResponse, error)
	ResisterPaymentConfirmed(ctx context.Context, in *PaymentConfirmedRequest, opts ...grpc.CallOption) (*PaymentConfirmedResponse, error)
}

type bookingClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingClient(cc grpc.ClientConnInterface) BookingClient {
	return &bookingClient{cc}
}

func (c *bookingClient) RegisterSearchFlight(ctx context.Context, in *SearchFlightRequest, opts ...grpc.CallOption) (*SearchFlightResponse, error) {
	out := new(SearchFlightResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterSearchFlight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterSearchSelect(ctx context.Context, in *SearchSelectRequest, opts ...grpc.CallOption) (*SearchSelectResponse, error) {
	out := new(SearchSelectResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterSearchSelect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterTravellerDetails(ctx context.Context, in *TravellerRequest, opts ...grpc.CallOption) (*TravellerResponse, error) {
	out := new(TravellerResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterTravellerDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterLoginRequest(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterLoginRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) VerifyUser(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/Booking/VerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterPNRLogin(ctx context.Context, in *PNRLoginRequest, opts ...grpc.CallOption) (*PNRLoginResponse, error) {
	out := new(PNRLoginResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterPNRLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterSelectSeat(ctx context.Context, in *SeatSelectRequest, opts ...grpc.CallOption) (*SeatSelectResponse, error) {
	out := new(SeatSelectResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterSelectSeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterConfirmBooking(ctx context.Context, in *ConfirmBookingRequest, opts ...grpc.CallOption) (*ConfirmBookingResponse, error) {
	out := new(ConfirmBookingResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterConfirmBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RegisterOnlinePayment(ctx context.Context, in *OnlinePaymentRequest, opts ...grpc.CallOption) (*OnlinePaymentResponse, error) {
	out := new(OnlinePaymentResponse)
	err := c.cc.Invoke(ctx, "/Booking/RegisterOnlinePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) ResisterPaymentConfirmed(ctx context.Context, in *PaymentConfirmedRequest, opts ...grpc.CallOption) (*PaymentConfirmedResponse, error) {
	out := new(PaymentConfirmedResponse)
	err := c.cc.Invoke(ctx, "/Booking/ResisterPaymentConfirmed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServer is the server API for Booking service.
// All implementations must embed UnimplementedBookingServer
// for forward compatibility
type BookingServer interface {
	RegisterSearchFlight(context.Context, *SearchFlightRequest) (*SearchFlightResponse, error)
	RegisterSearchSelect(context.Context, *SearchSelectRequest) (*SearchSelectResponse, error)
	RegisterTravellerDetails(context.Context, *TravellerRequest) (*TravellerResponse, error)
	RegisterLoginRequest(context.Context, *LoginRequest) (*LoginResponse, error)
	RegisterUser(context.Context, *UserRequest) (*UserResponse, error)
	VerifyUser(context.Context, *OTPRequest) (*UserResponse, error)
	// rpc calls for confirmed booking users
	RegisterPNRLogin(context.Context, *PNRLoginRequest) (*PNRLoginResponse, error)
	RegisterSelectSeat(context.Context, *SeatSelectRequest) (*SeatSelectResponse, error)
	// rpc calls for booking
	RegisterConfirmBooking(context.Context, *ConfirmBookingRequest) (*ConfirmBookingResponse, error)
	RegisterOnlinePayment(context.Context, *OnlinePaymentRequest) (*OnlinePaymentResponse, error)
	ResisterPaymentConfirmed(context.Context, *PaymentConfirmedRequest) (*PaymentConfirmedResponse, error)
	mustEmbedUnimplementedBookingServer()
}

// UnimplementedBookingServer must be embedded to have forward compatible implementations.
type UnimplementedBookingServer struct {
}

func (UnimplementedBookingServer) RegisterSearchFlight(context.Context, *SearchFlightRequest) (*SearchFlightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSearchFlight not implemented")
}
func (UnimplementedBookingServer) RegisterSearchSelect(context.Context, *SearchSelectRequest) (*SearchSelectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSearchSelect not implemented")
}
func (UnimplementedBookingServer) RegisterTravellerDetails(context.Context, *TravellerRequest) (*TravellerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTravellerDetails not implemented")
}
func (UnimplementedBookingServer) RegisterLoginRequest(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterLoginRequest not implemented")
}
func (UnimplementedBookingServer) RegisterUser(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedBookingServer) VerifyUser(context.Context, *OTPRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}
func (UnimplementedBookingServer) RegisterPNRLogin(context.Context, *PNRLoginRequest) (*PNRLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPNRLogin not implemented")
}
func (UnimplementedBookingServer) RegisterSelectSeat(context.Context, *SeatSelectRequest) (*SeatSelectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSelectSeat not implemented")
}
func (UnimplementedBookingServer) RegisterConfirmBooking(context.Context, *ConfirmBookingRequest) (*ConfirmBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterConfirmBooking not implemented")
}
func (UnimplementedBookingServer) RegisterOnlinePayment(context.Context, *OnlinePaymentRequest) (*OnlinePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterOnlinePayment not implemented")
}
func (UnimplementedBookingServer) ResisterPaymentConfirmed(context.Context, *PaymentConfirmedRequest) (*PaymentConfirmedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResisterPaymentConfirmed not implemented")
}
func (UnimplementedBookingServer) mustEmbedUnimplementedBookingServer() {}

// UnsafeBookingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingServer will
// result in compilation errors.
type UnsafeBookingServer interface {
	mustEmbedUnimplementedBookingServer()
}

func RegisterBookingServer(s grpc.ServiceRegistrar, srv BookingServer) {
	s.RegisterService(&Booking_ServiceDesc, srv)
}

func _Booking_RegisterSearchFlight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFlightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterSearchFlight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterSearchFlight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterSearchFlight(ctx, req.(*SearchFlightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterSearchSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterSearchSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterSearchSelect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterSearchSelect(ctx, req.(*SearchSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterTravellerDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TravellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterTravellerDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterTravellerDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterTravellerDetails(ctx, req.(*TravellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterLoginRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterLoginRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterLoginRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterLoginRequest(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).VerifyUser(ctx, req.(*OTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterPNRLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PNRLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterPNRLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterPNRLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterPNRLogin(ctx, req.(*PNRLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterSelectSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatSelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterSelectSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterSelectSeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterSelectSeat(ctx, req.(*SeatSelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterConfirmBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterConfirmBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterConfirmBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterConfirmBooking(ctx, req.(*ConfirmBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RegisterOnlinePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlinePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RegisterOnlinePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/RegisterOnlinePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RegisterOnlinePayment(ctx, req.(*OnlinePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_ResisterPaymentConfirmed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentConfirmedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).ResisterPaymentConfirmed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking/ResisterPaymentConfirmed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).ResisterPaymentConfirmed(ctx, req.(*PaymentConfirmedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Booking_ServiceDesc is the grpc.ServiceDesc for Booking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Booking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Booking",
	HandlerType: (*BookingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSearchFlight",
			Handler:    _Booking_RegisterSearchFlight_Handler,
		},
		{
			MethodName: "RegisterSearchSelect",
			Handler:    _Booking_RegisterSearchSelect_Handler,
		},
		{
			MethodName: "RegisterTravellerDetails",
			Handler:    _Booking_RegisterTravellerDetails_Handler,
		},
		{
			MethodName: "RegisterLoginRequest",
			Handler:    _Booking_RegisterLoginRequest_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Booking_RegisterUser_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _Booking_VerifyUser_Handler,
		},
		{
			MethodName: "RegisterPNRLogin",
			Handler:    _Booking_RegisterPNRLogin_Handler,
		},
		{
			MethodName: "RegisterSelectSeat",
			Handler:    _Booking_RegisterSelectSeat_Handler,
		},
		{
			MethodName: "RegisterConfirmBooking",
			Handler:    _Booking_RegisterConfirmBooking_Handler,
		},
		{
			MethodName: "RegisterOnlinePayment",
			Handler:    _Booking_RegisterOnlinePayment_Handler,
		},
		{
			MethodName: "ResisterPaymentConfirmed",
			Handler:    _Booking_ResisterPaymentConfirmed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking.proto",
}
